import { API_ENDPOINTS, GET_META_DATA, SET_DATA_KEY } from '../../constants';

export default [
  {
    Text: 'About Us',
    Navigation: 'AboutUs',
    dataKey: 'aboutUs',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'Our People',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'President',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'president',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Secretary',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'secretary',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Treasurer',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'treasurer',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Vice-Presidents',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'vice_presidents',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Advisory Board',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'advisory_board',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Resource Persons',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'resource_persons',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'Activities & Events',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'Conferences',
        Navigation: 'Events',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'conferences',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Forum',
        Navigation: 'Events',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'forums',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Upcoming Events',
        Navigation: 'Events',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'upconferences',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Workshops',
        Navigation: 'Events',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'workshop',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'Publications',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'Conference Proceedings',
        Navigation: '',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Journal',
        Navigation: '',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Submission Form',
        Navigation: '',
        authRequired: true,
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Working Paper Series',
        Navigation: '',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'Our Services',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'International Conferences',
        Navigation: 'Publications',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'conference',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'New datasets',
        Navigation: '',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Proof reading of manuscripts',
        Navigation: '',
        authRequired: true,
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Review of Papers',
        Navigation: '',
        authRequired: true,
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Submission of Working Papers',
        Navigation: '',
        authRequired: true,
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Conference Paper Submission',
        Navigation: '',
        authRequired: true,
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Editorial Services',
        Navigation: 'AboutUs',
        dataKey: 'editorial_services',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'News',
    Navigation: 'Publications',
    metaDataAction: GET_META_DATA,
    action: SET_DATA_KEY,
    dataKey: 'news',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'Partners',
    Navigation: 'Partners',
    metaDataAction: GET_META_DATA,
    action: SET_DATA_KEY,
    dataKey: 'partner',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'Gallery',
    Navigation: 'Gallery',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'FAQ',
    Navigation: 'FAQ',
    metaDataAction: GET_META_DATA,
    action: SET_DATA_KEY,
    dataKey: 'faq',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'Contact Us',
    Navigation: 'ContactUs',
    color: '#545454',
    cstmClass: '',
  },
];
