export default [
  {
    Text: 'About Us',
    Navigation: 'AboutUs',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'Our People',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'President',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Secretary',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Treasurer',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Vice-Presidents',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Advisory Board',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Resource Persons',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'Activities & Events',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'Conferences',
        Navigation: 'Events',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Forum',
        Navigation: 'Events',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Upcoming Events',
        Navigation: 'Events',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Workshops',
        Navigation: 'Events',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Credit Card Payment',
        Navigation: 'Events',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'Publications',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'Conference Proceedings',
        Navigation: 'Publications',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Journal',
        Navigation: 'Publications',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Submission Form',
        Navigation: 'Publications',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Working Paper Series',
        Navigation: 'Publications',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'Our Services',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'International Conferences',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'New datasets',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Proof reading of manuscripts',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Review of Papers',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Submission of Working Papers',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Conference Paper Submission',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Editorial Services',
        Navigation: 'Welcome',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'Membership',
    Navigation: 'Membership',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'News',
    Navigation: 'News',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'Partners',
    Navigation: 'Partners',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'Gallery',
    Navigation: 'Gallery',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'FAQ',
    Navigation: 'FAQ',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'Contact Us',
    Navigation: 'ContactUs',
    color: '#545454',
    cstmClass: '',
  },
];
