import { API_ENDPOINTS, GET_META_DATA, SET_DATA_KEY } from '../../constants';
import I18n from '../../i18n';

export default [
  {
    Text: 'AboutUs',
    Navigation: 'AboutUs',
    dataKey: 'aboutUs',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'OurPeople',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'President',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'president',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Secretary',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'secretary',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Treasurer',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'treasurer',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'VicePresidents',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'vice_presidents',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'AdvisoryBoard',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'advisory_board',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'ResourcePersons',
        Navigation: 'OurPeople',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        sub_url: API_ENDPOINTS.ourPeople,
        dataKey: 'resource_persons',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'ActivitiesNEvents',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'Conferences',
        Navigation: 'Events',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'conferences',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Forum',
        Navigation: 'Events',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'forums',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'UpcomingEvents',
        Navigation: 'Events',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'upconferences',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Workshops',
        Navigation: 'Events',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'workshop',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'Publications',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'ConferenceProceedings',
        Navigation: 'Publications',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'conferenceproceeding',
        extraKey: 'conference_procedding',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'Journal',
        Navigation: 'Publications',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'journal',
        extraKey: 'records',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'SubmissionForm',
        Navigation: 'ContactUs',
        dataKey: 'submission-form',
        authRequired: true,
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'WorkingPaperSeries',
        Navigation: 'Publications',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'working_paper_series',
        extraKey: 'records',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'OurServices',
    color: '#545454',
    cstmClass: '',
    subMenu: [
      {
        Text: 'InternationalConferences',
        Navigation: 'Publications',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'conference',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'NewDatasets',
        Navigation: 'Publications',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'new_datasets',
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'ProofReadingOfManuscripts',
        Navigation: 'ContactUs',
        dataKey: 'proof-reading-of-manuscripts',
        authRequired: true,
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'ReviewOfPapers',
        Navigation: 'ContactUs',
        dataKey: 'review-of-papers',
        authRequired: true,
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'SubmissionOfWorkingPapers',
        Navigation: 'ContactUs',
        dataKey: 'submission-of-working-papers',
        authRequired: true,
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'ConferencePaperSubmission',
        Navigation: 'Publications',
        metaDataAction: GET_META_DATA,
        action: SET_DATA_KEY,
        dataKey: 'conference_paper',
        extraKey: 'conference_papers',
        authRequired: true,
        color: '#545454',
        cstmClass: '',
      },
      {
        Text: 'EditorialServices',
        Navigation: 'AboutUs',
        dataKey: 'editorial_services',
        color: '#545454',
        cstmClass: '',
      },
    ],
  },
  {
    Text: 'News',
    Navigation: 'Publications',
    metaDataAction: GET_META_DATA,
    action: SET_DATA_KEY,
    dataKey: 'news',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'Partners',
    Navigation: 'Partners',
    metaDataAction: GET_META_DATA,
    action: SET_DATA_KEY,
    dataKey: 'partner',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'Gallery',
    Navigation: 'Gallery',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'FAQ',
    Navigation: 'FAQ',
    metaDataAction: GET_META_DATA,
    action: SET_DATA_KEY,
    dataKey: 'faq',
    color: '#545454',
    cstmClass: '',
  },
  {
    Text: 'ContactUs',
    Navigation: 'ContactUs',
    dataKey: 'constact-us-form',
    color: '#545454',
    cstmClass: '',
  },
];
