export const GET_BOARDING_DATA = 'GET_BOARDING_DATA';
export const BOARDING_DATA_SUCCESS = 'BOARDING_DATA_SUCCESS';
export const BOARDING_DATA_FAILURE = 'BOARDING_DATA_FAILURE';

export const GET_BOARDING_IMAGES = 'GET_BOARDING_IMAGES';
export const BOARDING_IMAGES_SUCCESS = 'BOARDING_IMAGES_SUCCESS';
export const BOARDING_IMAGES_FAILURE = 'BOARDING_IMAGES_FAILURE';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const SET_USER_SESSION = 'SET_USER_SESSION';
export const SIGN_OUT = 'SIGN_OUT';

export const MY_ACCOUNT_SUCCESS = 'MY_ACCOUNT_SUCCESS';
export const MY_ACCOUNT__FAILURE = 'MY_ACCOUNT__FAILURE';
export const SET_ACCOUNT_MENU = 'SET_ACCOUNT_MENU';

export const DISPLAY_DATA_SCREEN = 'DISPLAY_DATA_SCREEN';
export const HIDE_DATA_SCREEN = 'HIDE_DATA_SCREEN';

export const GET_OUR_PEOPLE = 'GET_OUR_PEOPLE';
export const OUR_PEOPLE_SUCCESS = 'OUR_PEOPLE_SUCCESS';
export const OUR_PEOPLE_FAILURE = 'OUR_PEOPLE_FAILURE';